// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUC3a3ks48jNntVFp98alQ1Ar_cvgpiM',
    appId: '1:428944702893:web:699aebc99494f9e3273524',
    messagingSenderId: '428944702893',
    projectId: 'talabat-online',
    authDomain: 'talabat-online.firebaseapp.com',
    storageBucket: 'talabat-online.firebasestorage.app',
    measurementId: 'G-XPP07EE8T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2C2gmgIxYvMq_RtbSNdovgZY59LVxX0A',
    appId: '1:428944702893:android:9d00d1a2e227758f273524',
    messagingSenderId: '428944702893',
    projectId: 'talabat-online',
    storageBucket: 'talabat-online.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4suIZkp2MdfJgjkixsiCX7qIpJEkl3s',
    appId: '1:428944702893:ios:5d7bee57ad8e7350273524',
    messagingSenderId: '428944702893',
    projectId: 'talabat-online',
    storageBucket: 'talabat-online.firebasestorage.app',
    iosBundleId: 'com.example.talabatOnline',
  );
}
